### ISSUE TITLE
"Winners" shown in blue before they win

### ISSUE THREAD

**Issue by ggordn3r** [fairvotereform/RankIt#154]
In this poll, it looks as if 5 winners have been chosen by round 5:
https://rankit.skelpo.com/results/7EsrKw7yUlgHD33T6CgP/5

But if I'm reading this right, Georgetown is the only winner because it's the only choice to clear 17%. So why do the choices with 16.7% (3 votes) in the first round all light up blue as if they had been elected?

It's definitely a bug, I'm just not sure what's causing it.

**Comment by proggeramlug** [comment]
Hmm, definitely a mean bug: The actual winning-percentage is 16.6666666667%.

All those highlighted have a percentage of 16.66666667%. However, in the top line (and the threshold line), we are rounding up to the next actual %. So 17.

That being said, there is only one that is actually higher than the 16.666667% and that is the sole winner.

So how do we want to do it? I've added some rounding (to be consistent) in the graph logic as well that takes out the bug here, but it might reappear elsewhere. Thoughts?

**Comment by ggordn3r** [comment]
Got it. The actual winning percentage (the 16.6666666667%) is what should determine winners. The only reason we are rounding in the top line and threshold line is to keep the visuals simple. They should not affect the tabulation.

I think the choices were being correctly elected, but their bars showed 16.7% while the visible threshold was 17%. Can that be fixed by rounding to the nearest whole percentage? If so, go ahead and add that. We already round the vote counts.

**Comment by proggeramlug** [comment]
That's already the case here: https://rankit.skelpo.com/results/7EsrKw7yUlgHD33T6CgP/5

**Comment by ggordn3r** [comment]
Adding a screenshot for clarity:

![Screenshot (129)](https://user-images.githubusercontent.com/10144772/90297944-5013fa00-de5e-11ea-8070-2d86da9a46ff.png)

**Comment by proggeramlug** [comment]
Check it out now!

**Comment by ggordn3r** [comment]
Ok, so just to be clear: none of the 17% ones are actually declared winners? They're just exactly at the threshold?

Also, why isn't Georgetown showing up in the list of winners? See screenshot above.

**Comment by proggeramlug** [comment]
Your screenshot is from an older status of the votes/poll. Georgetown is actually the winner but with a higher percentage.

the others are exactly _at_ the threshold though

**Comment by proggeramlug** [comment]
it's less likely if there are more votes, if we have less than 20 votes this might happen every so often (being exactly at the threshold)

**Comment by ggordn3r** [comment]
Ok, I understand the "right at the threshold" part. 3/18 = 16.66 repeating.

BUT I'm still not seeing Georgetown mentioned in the final list of winners:
https://rankit.skelpo.com/results/7EsrKw7yUlgHD33T6CgP/summary

It lists 4 winners instead of 5. Georgetown should be the 5th.

**Comment by proggeramlug** [comment]
Okay, the wording is misleading here. And the vote count is too little for it to be meaningful. Because:
Georgetown won, not part of the tie: 4 votes
The other 4 are actually tied with 3 votes each. The threshold is 4, so only Georgetown got to it.

With us rounding and the total vote count being only 18 this is not super surprising. How do we want to address this though? It _should_ (I think) say something like: Georgetown won and the (...) are tied. Or so.

**Comment by ggordn3r** [comment]
I'm going to kick this to the Fairvote developer and ask him. The algorithm
should be running until 5 winners have been chosen, period. But it looks
like it stops short of that in this case. I'm not sure if that's a feature
or a bug.

**Comment by proggeramlug** [comment]
Well, it is 5 winners in total. 4 of them are tied though, but one (Georgetown) actually has one vote more than the rest.

**Comment by ggordn3r** [comment]
After our phone discussion, I understand that this is not an algorithm issue but a messaging issue: we never anticipated mentioning clear winners in a later-stage tie, which is why the final round appears to "forget" Georgetown winning.

Let's try mentioning clear winners again, such that the first paragraph of the [Poll Summary](https://rankit.skelpo.com/results/7EsrKw7yUlgHD33T6CgP/summary) (final results) reads:
_After 6 rounds, Georgetown won and there was a tie between DuPont Circle, Columbia Heights, Downtown, and Adams Morgan._

**Comment by proggeramlug** [comment]
Check it out now: https://rankit.skelpo.com/results/7EsrKw7yUlgHD33T6CgP/summary

We need to make sure this does not have negative effects elsewhere ...

**Comment by ggordn3r** [comment]
I'll keep an eye on it for testing.
